apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    application: mysql
spec:
  containers:
    - name: mysql	  
      image: mysql:5.6
      env:
      - name: MYSQL_DATABASE
        valueForm:
          secretKeyRef:
            key: db_host
            name: mysecret
      - name: MYSQL_USER
        valueForm:
          secretKeyRef:
            key: username
            name: mysecret
      - name: MYSQL_PASSWORD
        valueForm:
          secretKeyRef:
            key: password
            name:mysecret
      resource:
        request:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        tcpSocket:  # test wordpress alive
          port: 3306
      redinessProbe: 
        httpGet:  # test wordpress alive, and different from livenessProbe test method
          path: /healthy
          port: 3306
      ports:
      - containerPort: 3306
        name: mysql
        protocol: TCP        
      
  restartPolicy: Always  #kubelet always restart 