apiVersion: v1
kind: Pod
metadata:
  name: Nginx-pod
  labels:
    application: nginx
spec:
  containers:
    - name: nginx	  
      image: nginx:latest
      volumeMounts:
        - name: share-logs
          mountPath: /var/log/nginx
       - mountPath: /etc/nginx/
          name: nginx-conf
          readOnly: true
    - name: fluentd	
      image: fluentd:latest
      volumeMounts:
        - name: share-logs
          mountPath: /logs
       - mountPath: /fluentd/etc
          name: fluent-conf
          readOnly: true    
  volumes:
    - name: share-logs
      emptyDir: {}
    - configMap:
        #items:
         # - key: nginx.conf # key name in configmap
          #  path: nginx.conf # file name in container
        name: nginx-conf
      name: nginx-conf
    - configMap:
        items:
          - key: fluent.conf
            path: fluent.conf
        name: fluent-conf
      name: fluent-conf
