apiVersion: v1
kind: Pod
metadata:
  name: Wordpress-pod
  labels:
    application: wordpress
spec:
  containers:
    - name: wordpress	  
      image: wordpress:latest
      env:
      - name: WORDPRESS_DB_HOST
        valueForm:
          secretKeyRef:
            key: db_host
            name: mysecret
      - name: WORDPRESS_DB_NAME
        valueForm:
          secretKeyRef:
            key: db_name
            name: mysecret
      - name: WORDPRESS_DB_USER
        valueForm:
          secretKeyRef:
            key: username
            name:mysecret
      - name: WORDPRESS_DB_PASSWORD
        valueForm:
          secretKeyRef:
            key: password
            name:mysecret
      resource:
        request:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        tcpSocket:  # test mysql alive
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 2  
      redinessProbe: 
        # test mysql alive, and different from livenessProbe test method
        exec:
          command:
          - cat
          - readme.html
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 2 
  restartPolicy: Always  #kubelet always restart      		  


 